# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

alias raid_tunnel='/home/zyc/shell/raid_tunnel.sh'
alias raid_tunnel_remote='/home/zyc/shell/raid_tunnel_remote.sh'

#256color
export TERM=xterm-256color

PYTHON_INCLUDE_DIRS=/usr/include/python2.7 
PYTHON_LIBRARIES=/usr/lib/python2.7/config-x86_64-linux-gnu/libpython2.7.so

#shell
export PATH=$PATH:/home/zyc/shell

#scala
export PATH=$PATH:/home/zyc/Documents/Tools/scala-2.11.8/bin/

#go
export GOROOT=/home/zyc/Documents/Tools/go
export GOPATH=/home/zyc/Documents/Tools/gopath/
export PATH=$PATH:$GOROOT/bin
export PATH=$PATH:$GOPATH/bin


#java path
#export JAVA_PATH=/home/zyc/Documents/Tools/Java/jdk1.7.0_25
export JAVA_PATH=/home/zyc/Documents/Tools/Java/jdk1.8.0_40
export JAVA_HOME=$JAVA_PATH
export PATH=$JAVA_PATH/bin/:$PATH
export SDK=~/Documents/Tools/android_sdk
export NDK=~/Documents/Tools/android-ndk-r10c
export NDKR10C=~/Documents/Tools/android-ndk-r10c
export NDKR9C=~/Documents/Tools/android-ndk-r10c

#jni lib
export JNI_PATH=~/Documents/work/JNI
export LD_LIBRARY_PATH=$JNI_PATH:$LD_LIBRARY_PATH

#hadoop
export HADOOP_HOME=/home/zyc/Documents/Tools/hadoop-2.6.0
export HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop
export HADOOP_MAPRED_HOME=$HADOOP_HOME 
export HADOOP_COMMON_HOME=$HADOOP_HOME 
export HADOOP_HDFS_HOME=$HADOOP_HOME 
export YARN_HOME=$HADOOP_HOME 
export HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_HOME/lib/native 
export PATH=$PATH:$HADOOP_HOME/sbin:$HADOOP_HOME/bin 
export HADOOP_INSTALL=$HADOOP_HOME 

#spark
export SPARK_HOME=/home/zyc/Documents/Tools/spark-2.0.0-bin-hadoop2.7
export PATH=$PATH:$SPARK_HOME/bin/:$SPARK_HOME/sbin

#drill
export DRILL_HOME=/home/zyc/Documents/Tools/apache-drill-1.6.0
export PATH=$PATH:$DRILL_HOME/bin/

#pyspark ipython
#export PYSPARK_DRIVER_PYTHON=jupyter
#export PYSPARK_DRIVER_PYTHON_OPTS='notebook' pyspark

myrm(){ D=~/.trash/$(date +%Y%m); mkdir -p $D;  mv "$@" $D/$(date +%Y%m%d%H%M)_temp && echo "moved to $D ok"; }
alias rm="myrm"

#cd ..
alias ..1="cd .."
alias ..2="cd ../.."
alias ..3="cd ../../.."
alias ..4="cd ../../../.."
alias ..5="cd ../../../../.."
alias ..6="cd ../../../../../.."
alias ..7="cd ../../../../../../.."
alias ..8="cd ../../../../../../../.."

#google code jam: distributed
export PATH=$PATH:/home/zyc/Documents/code/acm/gcj#2016/dcj/dcj_linux


# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi
#export PYTHONPATH="${PYTHONPATH}:/home/zyc/Documents/code/python/zyc_lib"

# added by Anaconda2 4.2.0 installer
export PATH="/home/zyc/Documents/Tools/anaconda2/bin:$PATH"

# added by Anaconda3 installer
export PATH="/home/zyc/anaconda3/bin:$PATH"
